<a href="https://colab.research.google.com/github/tuli-pen/Python_de_0_a_NLP/blob/master/Leccion_01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Curso Python "De 0 a NLP"**

*Tuli Peña Melo, enero de 2024*
# Lección 01 | Numpy

In [ ]:
# Abreviatura usual para Numpy
import numpy as np

### Funciones matemáticas

In [ ]:
# Funciones trigonométricas
mi_coseno = np.cos(0)
print(mi_coseno)

1.0


In [ ]:
# Raices cuadradas
mi_raiz = np.sqrt(16)
mi_raiz

4.0

In [ ]:
# Potenciación a cualquier exponente
mi_potencia = np.power(2,3)
mi_potencia

4.0

### Arrays: la estructura de datos central en Numpy



In [ ]:
# Array de 1 dimensión
primer_array = np.array([1, 2, 3, 4])

# Imprimámoslo
print(primer_array)

[1 2 3 4]


In [ ]:
# Array de 2 dimensiones
segundo_array = np.array([[1, 2, 3], [4, 5, 6]])

# Imprimámoslo
print(segundo_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Podemos comprobar el tipo de datos que contiene
segundo_array.dtype

dtype('int64')

In [ ]:
# Podemos consultar cuál es la dimensión del array
segundo_array.ndim

2

In [ ]:
# ".shape" nos devuelve una tupla con la cantidad de elementos que tiene cada dimensión
segundo_array.shape

(2, 3)

In [ ]:
# Array de 3 dimensiones
tercer_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Imprimámoslo
print(tercer_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Verifiquemos su dimensión y su shape
print(tercer_array.ndim)
print(tercer_array.shape)

3
(2, 2, 3)


In [ ]:
# Guardemos su shape en varias variables
a, b, c = tercer_array.shape
print(a)
print(b)
print(c)

2
2
3


### Acceder a elementos de un array por su índice

In [ ]:
# Creamos un array de 2 dimensiones
mi_array = np.array([[1, 2, 3], [4, 5, 6]])
print(mi_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Imprimimos el segundo elemento de la primera fila
mi_array[0,1]

2

### —— Mini Test ——

In [ ]:
# Crea un array de 3 filas y 2 columnas lleno de solo unos

# Tu código aquí:



In [ ]:
# Imprime el número 8 dentro del array dado
el_array = np.array([[2, 2, 8, 2], [2, 2, 2, 2]])

# Tu código aquí:



### Funciones matemáticas, ahora sobre arrays

In [ ]:
mi_array = np.array([1, 2, 3, 4])
print(mi_array.dtype)

int64


In [ ]:
# Funciones trigonométricas
coseno = np.cos(mi_array)
print(coseno)
print(coseno.dtype)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
float64


In [ ]:
# Raices cuadradas
raiz = np.sqrt(mi_array)
print(raiz)
print(raiz.dtype)

[1.         1.41421356 1.73205081 2.        ]
float64


In [ ]:
# Potenciación a cualquier exponente
potencia = np.power(mi_array,3)
print(potencia)
print(potencia.dtype)

[ 1  8 27 64]
int64


### Operaciones sobre un array que devuelven un valor

In [ ]:
mi_array = np.array([1, 2, 6])
print(mi_array + 3)

[4 5 9]


In [ ]:
# Devuelve la suma de todos los valores en del array
np.sum(mi_array)

9

In [ ]:
# Devulve en valor máximo en el array
np.max(mi_array)

6

In [ ]:
# Devulve en valor mínimo en el array
np.min(mi_array)

1

In [ ]:
# Devuelve el promedio de todos los valores en el array
np.average(mi_array)

3.0

### Creación de arrays

**Array de ceros o de unos**

In [ ]:
# Array de ceros
# A ".zeros" le pasaremos la shape que queremos
ceros = np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array de unos
# A ".ones" le pasaremos la shape que queremos
ceros = np.ones((2,3))
print(ceros)
print(ceros.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


**Array identidad**

Una matriz identidad siempre debe ser cuadrada, por lo que sólo es necesario indicar una dimensión.

In [ ]:
# Se puede usar ".identity" o ".eye"
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Array creado con un rango**

Hay dos formas de hacer esto:
* **np.arange** permite especificar el tamaño del paso
* **np.linspace** permite especificar la cantidad de puntos que deseas en el array

#### np.arange

Sintaxis: **np.arange(comienzo, final, tamaño del paso)**

* ¡El número final no se incluye, siempre llega hasta el número anterior! (Si quieres que llegue hasta 8 debes poner 9 como número final)
* El comienzo por defecto es 0 y el tamaño de paso por defecto es 1.

In [ ]:
# Definamos un array que vaya de 2 a 7:
a = np.arange(2, 8)
print(a)

[2 3 4 5 6 7]


In [ ]:
# Definamos un array que vaya de 0 a 9, de 3 en 3
b = np.arange(0, 10, 3)
print(b)

[0 3 6 9]


#### np.linspace

Sintaxis: **np.linspace(comienzo, final, cantidad de pasos)**

Se incluye el valor del comienzo y también el del final.

In [ ]:
# Definamos un array que vaya de 0 a 10, con 5 pasos
c = np.linspace(0, 11, 5)
print(c)

[ 0.    2.75  5.5   8.25 11.  ]


### Manipulación de un array
*Estas operaciones se aplican a un array y devuelven un array.*


**Reshape**

In [ ]:
# Crear un array de una dimensión con 12 elementos (de 0 a 12)
array_original = np.arange(0, 12)
print("Array original:")
print(array_original)

# Redimensionar el array para que tenga 3 filas y 4 columnas
array_redimensionado = array_original.reshape(3, 4)
print("\nArray redimensionado:")
print(array_redimensionado)

Array original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Array redimensionado:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Transpose**

In [ ]:
mi_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array original:")
print(mi_array)

transpuesto = mi_array.transpose()
print("\nArray transpuesto:")
print(transpuesto)

Array original:
[[1 2 3]
 [4 5 6]]

Array transpuesto:
[[1 4]
 [2 5]
 [3 6]]


### Operaciones entre arrays:

*Estas operaciones se aplican a 2 arrays y devuelven un array.*

**Operaciones básicas**

In [ ]:
# Creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 31)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30]


In [ ]:
# Los sumamos (elemento por elemento)
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
# Los multiplicamos (elemento por elemento)
arr1 * arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [ ]:
# Los dividimos (elemento por elemento)
arr1 / arr2

array([0.        , 0.04761905, 0.09090909, 0.13043478, 0.16666667,
       0.2       , 0.23076923, 0.25925926, 0.28571429, 0.31034483,
       0.33333333])

**Comparaciones**

In [ ]:
# >,<
arr1 < arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
# ==
arr1 == arr2

array([False, False, False, False, False, False, False, False, False,
       False, False])

**Operación especial: .dot**

Corresponde a la operación Producto Matricial si estamos trabajando con arrays de más de una dimensión y corresponde al Producto Punto de dos arrays si ambos son de una dimensión.


In [ ]:
# Crear dos matrices
matriz1 = np.array([[1, 2, 3],
                    [4, 4, 4]])
print("Matriz 1:")
print(matriz1)

matriz2 = np.array([[2, 3],
                    [4, 0],
                    [1, 2]])

print("\nMatriz 2:")
print(matriz2)

Matriz 1:
[[1 2 3]
 [4 4 4]]

Matriz 2:
[[2 3]
 [4 0]
 [1 2]]


In [ ]:
# Calcular el producto matricial
producto_matricial = np.dot(matriz1, matriz2)

print("Producto matricial:")
print(producto_matricial)

Producto matricial:
[[13  9]
 [28 20]]


### —— Mini Test ——

In [ ]:
# A continuación hay 3 vectores, que representan embeddings de 3 palabras
embedding_gato = np.array([4, 2, 3])
embedding_perro = np.array([5, 2, 4])
embedding_sol = np.array([-43, -2, -37])

# Calcula e imprime el producto punto de cada par de esos embeddings,
#para saber cuáles dos palabras están más cercanas entre ellas

# Tu código aquí:



36 -367 -287


### Generación de números aleatorios
Siempre que vayamos a generar números aleatorios debemos crear un generador.

* Un "generador" es un objeto instanciado de la clase **np.random.Generator**

* La forma recomendada de crear un generador es llamando a la función **np.random.default_rng()**, esa función nos devuelve un objeto de tipo generador y ese lo guardamos en la variable **rng** por convención

In [ ]:
# Debemos escribir esto siempre antes de crear números aleatorios:
rng = np.random.default_rng()

# Vemos  que dentro de "rng" quedó un generador:
print(rng)

**rng.random**

Función dentro de nuestro generador que sirve para generar números aleatorios entre 0 y 1 de tipo float

In [ ]:
rng = np.random.default_rng()

# Si llamas la función sin pasarle nada te devuelve un sólo número aleatorio
random_number = rng.random()
print(random_number)

0.8726712061261317


In [ ]:
rng = np.random.default_rng()

# Si llamas la función pasándole un shape te devuelve un
# array con esa shape lleno de números aleatorios entre 0 y 1
random_array = rng.random((3, 2))
print(random_array)

[[0.58385982 0.93185017]
 [0.3646358  0.04566057]
 [0.88104636 0.5507225 ]]


**rng.integers**

Función dentro de nuestro generador que sirve para generar números aleatorios de tipo int entre dos números que le digamos

Sintaxis: **rng.integers(*inicio*, *fin*, size= *shape que queramos*)**
* inicio si se incluye
* final no se incluye (va hasta el anterior)

In [ ]:
rng = np.random.default_rng()

# Si no le pasas shape te devuelve un solo número
random_integer = rng.integers(1, 10)
print(random_integer)

9


In [ ]:
rng = np.random.default_rng()

# Si le pasas un shape te devuelve un array
random_int_array = rng.integers(1, 10, size=(3, 2))
print(random_int_array)

[[3 3]
 [7 6]
 [1 5]]


### —— Mini Test ——

In [ ]:
# Importa numpy
# Luego crea un generador, guárdalo en la variable rng e imprime la variable rng
# Después, usando ese generador crea un array de 2 filas y 5 columnas de números aleatorios entre 0 y 1
# Luego imprime el array que creaste

# Tú código aquí:



In [ ]:
# Aquí tienes una lista de palabras
palabras = ['como', 'hipotenusa', 'francisco',
            'saludable', 'pero', 'no']

# Estas son las probabilidades de que cada una de esas palabras
# sea la segunda palabra, dado que la primera palabra es 'Hola'
probs_dado_hola = np.array([[70, 4, 40],
                            [8, 6, 2]])

# Crea un array de números aleatorios entre 2 y 5, súmalo a las probabilidades y luego imprímelo

# Tu código aquí:



## Cheat-Sheet Numpy

### Funciones matemáticas:

*Se pueden aplicar a un elemento o a un array.*

*Si se aplican a un elemento devuelven un elemento, si se aplican a un array devuelven un array.*

* **np.sin, np.cos, np.tan:** Funciones trigonométricas.
* **np.sqrt:** Raíz cuadrada.
* **np.power:** Potenciación a cualquier exponente.

### Creación de arrays:
* **np.array:** Crea un array a partir de una lista o tupla.
* **np.zeros:** Crea un array de ceros.
* **np.ones:** Crea un array de unos.
* **np.identity:** Crea un array identidad.
* **np.arange:** Crea un array con valores espaciados uniformemente dentro de un rango.
* **np.linspace:** Crea un array con valores espaciados uniformemente entre dos números.

### Operaciones sobre un array que devuelven un valor:
* **np.sum:** Devuelve la suma de todos los valores en del array.
* **np.max:** Devulve en valor máximo en el array.
* **np.min:** Devulve en valor mínimo en el array.
* **np.average:** Devuelve el promedio de todos los valores en el array.

### Manipulación de un array:
*Estas operaciones se aplican a un array y devuelven un array.*
* **np.reshape:** Cambia la forma de un array.
* **np.transpose:** Transpone un array.

### Operaciones entre arrays:

*Estas operaciones se aplican a 2 arrays y devuelven un array.*

* **arr1 + arr2:** Suma dos arrays elemento por elemento.
* **arr1 - arr2:** Resta dos arrays elemento por elemento.
* **arr1 * arr2:** Multiplica dos arrays elemento por elemento.
* **arr1 / arr2:** Divide dos arrays elemento por elemento.

Operación especial:

*Esta operación se aplica a 2 arrays y devuelve un valor.*
* **np.dot:** Corresponde a la operación Producto Matricial si estamos trabajando con arrays de más de una dimensión y corresponde al Producto Punto de dos arrays si ambos son de una dimensión.

### Generación de números aleatorios

*Primero hay que crear un generador de esta forma:*

***rng = np.random.default_rng()***

*Dentro de rng quedó guardado nuestro generador.*

*Luego podemos usar funciones de ese generador para generar números aleatorios.*

* **rng.random:** sirve para generar números aleatorios entre 0 y 1 de tipo float
* **rng.integers:** sirve para generar números aleatorios de tipo int entre dos números que le digamos